/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const EnterNameLazyImport = createFileRoute('/enter-name')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const EnterNameLazyRoute = EnterNameLazyImport.update({
  path: '/enter-name',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/enter-name.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/enter-name': {
      id: '/enter-name'
      path: '/enter-name'
      fullPath: '/enter-name'
      preLoaderRoute: typeof EnterNameLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  EnterNameLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/enter-name"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/enter-name": {
      "filePath": "enter-name.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
